import { getDb } from '../db';
import { ensureExamSubmissionExists } from '../db/planner-exams';
import { detectSubjectsFromEventText } from '../config/subjects';
import { getDateInMoscow } from './planner';

const SYNTHETIC_CALENDAR_ID = 'synthetic';
const SYNTHETIC_CALENDAR_NAME = 'Synthetic (internal)';
const EXAMS_KEYWORD = 'exams';

function addDaysIso(dateIso: string, days: number): string {
  const d = new Date(`${dateIso}T00:00:00.000Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

function compareIso(a: string, b: string): number {
  return a.localeCompare(b);
}

function ensureSyntheticCalendarConfigId(): number {
  const db = getDb();
  const existing = db
    .prepare('SELECT id FROM calendar_config WHERE calendar_id = ? ORDER BY id LIMIT 1')
    .get(SYNTHETIC_CALENDAR_ID) as { id: number } | undefined;
  if (existing) return existing.id;

  const res = db
    .prepare(
      `INSERT INTO calendar_config (calendar_id, name, enabled, sync_error)
       VALUES (?, ?, 0, 0)`
    )
    .run(SYNTHETIC_CALENDAR_ID, SYNTHETIC_CALENDAR_NAME);
  return Number(res.lastInsertRowid);
}

function ensureSyntheticEnglishEventForDate(params: { dateIso: string; anchorEventId: number }): number {
  const db = getDb();
  const calendarConfigId = ensureSyntheticCalendarConfigId();
  const googleEventId = `synthetic:english:+3d:${params.anchorEventId}`;
  const existing = db
    .prepare(
      `SELECT id
       FROM calendar_events
       WHERE calendar_config_id = ? AND google_event_id = ?`
    )
    .get(calendarConfigId, googleEventId) as { id: number } | undefined;
  if (existing) return existing.id;

  // Важно:
  // - "exams" нужен, чтобы это воспринималось как exams-источник
  // - "self-study" нужен, чтобы Job2 не рассылал 15m/5m по этим событиям
  const title = 'English self-study (+3d) (exams)';
  const description = `synthetic exams; self-study; generated by bot; anchor_event_id=${params.anchorEventId}`;
  const startAt = `${params.dateIso}T00:00:00.000Z`;
  const endAt = `${params.dateIso}T01:00:00.000Z`;

  const res = db
    .prepare(
      `INSERT INTO calendar_events
       (calendar_config_id, google_event_id, title, description, start_at, end_at, raw_json, status)
       VALUES (?, ?, ?, ?, ?, ?, NULL, 'active')`
    )
    .run(calendarConfigId, googleEventId, title, description, startAt, endAt);
  const eventId = Number(res.lastInsertRowid);

  db.prepare('INSERT OR IGNORE INTO event_subjects (event_id, subject_key) VALUES (?, ?)').run(eventId, 'english');
  return eventId;
}

function getEligibleEnglishStudentIds(): number[] {
  const db = getDb();
  const rows = db
    .prepare(
      `SELECT DISTINCT s.id AS student_id
       FROM students s
       WHERE s.notify_dm = 1
         AND s.dm_blocked = 0
         AND EXISTS (
           SELECT 1 FROM student_subjects ss
           WHERE ss.student_id = s.id AND ss.subject_key = 'english'
         )`
    )
    .all() as Array<{ student_id: number }>;
  return rows.map((r) => r.student_id);
}

function findEnglishExamsAnchorEvent(params: {
  centerIso: string; // Moscow YYYY-MM-DD
  daysBack: number;
  daysForward: number;
}): { anchorEventId: number; anchorStartAt: string; anchorLessonDateMoscow: string } | null {
  const db = getDb();
  const fromIso = `${addDaysIso(params.centerIso, -params.daysBack)}T00:00:00.000Z`;
  const toIso = `${addDaysIso(params.centerIso, params.daysForward)}T23:59:59.999Z`;

  // Якорь: реальные english exams события (не synthetic), чтобы "среда → суббота" было привязано к календарю.
  // Важно: исключаем наш synthetic календарь по calendar_id = 'synthetic'.
  const rows = db
    .prepare(
      `SELECT ce.id, ce.start_at, ce.title, ce.description
       FROM calendar_events ce
       JOIN calendar_config cc ON cc.id = ce.calendar_config_id
       WHERE ce.status = 'active'
         AND cc.calendar_id != ?
         AND ce.start_at >= ? AND ce.start_at <= ?
         AND (
           LOWER(COALESCE(ce.title,'')) LIKE '%' || LOWER(?) || '%'
           OR LOWER(COALESCE(ce.description,'')) LIKE '%' || LOWER(?) || '%'
         )
       ORDER BY ce.start_at`
    )
    .all(SYNTHETIC_CALENDAR_ID, fromIso, toIso, EXAMS_KEYWORD, EXAMS_KEYWORD) as Array<{
    id: number;
    start_at: string;
    title: string;
    description: string | null;
  }>;

  if (!rows.length) return null;

  // Детектим предметы on-the-fly (на случай, если event_subjects ещё не заполнены джобами).
  // Заодно кэшируем в event_subjects для последующих запусков.
  const englishRows: Array<{ id: number; start_at: string }> = [];
  for (const r of rows) {
    const subjects = detectSubjectsFromEventText(r.title, r.description);
    for (const sk of subjects) {
      db.prepare('INSERT OR IGNORE INTO event_subjects (event_id, subject_key) VALUES (?, ?)').run(r.id, sk);
    }
    if (subjects.includes('english')) {
      englishRows.push({ id: r.id, start_at: r.start_at });
    }
  }

  if (!englishRows.length) return null;

  // Вариант (2): выбираем ближайший к todayMoscow.
  // Предпочтение: последний прошедший (<= center), иначе ближайший будущий (> center).
  const centerZ = `${params.centerIso}T00:00:00.000Z`;
  const past = englishRows.filter((r) => r.start_at <= centerZ);
  const future = englishRows.filter((r) => r.start_at > centerZ);
  const anchor = past.length ? past[past.length - 1] : future[0];
  const lessonDateMoscow = new Date(anchor.start_at).toLocaleDateString('en-CA', { timeZone: 'Europe/Moscow' });
  return { anchorEventId: anchor.id, anchorStartAt: anchor.start_at, anchorLessonDateMoscow: lessonDateMoscow };
}

export function ensureEnglishSyntheticExamsPlus3d(options?: {
  centerIso?: string; // YYYY-MM-DD (Moscow)
  daysBack?: number; // 7
  daysForward?: number; // 7
  plusDays?: number; // 3
}): {
  anchorEventId: number | null;
  anchorLessonDate: string | null;
  syntheticLessonDate: string | null;
  eventsEnsured: number;
  pairsEnsured: number;
  eligibleStudents: number;
} {
  const centerIso = options?.centerIso ?? getDateInMoscow();
  const daysBack = options?.daysBack ?? 7;
  const daysForward = options?.daysForward ?? 7;
  const plusDays = options?.plusDays ?? 3;

  const anchor = findEnglishExamsAnchorEvent({ centerIso, daysBack, daysForward });
  if (!anchor) {
    return {
      anchorEventId: null,
      anchorLessonDate: null,
      syntheticLessonDate: null,
      eventsEnsured: 0,
      pairsEnsured: 0,
      eligibleStudents: 0,
    };
  }

  const syntheticDateIso = addDaysIso(anchor.anchorLessonDateMoscow, plusDays);
  const studentIds = getEligibleEnglishStudentIds();

  const eventId = ensureSyntheticEnglishEventForDate({ dateIso: syntheticDateIso, anchorEventId: anchor.anchorEventId });
  let pairsEnsured = 0;
  for (const studentId of studentIds) {
    ensureExamSubmissionExists({
      studentId,
      lessonEventId: eventId,
      kind: 'lesson',
      lessonDate: syntheticDateIso,
      subjectKey: 'english',
    });
    ensureExamSubmissionExists({
      studentId,
      lessonEventId: eventId,
      kind: 'homework',
      lessonDate: syntheticDateIso,
      subjectKey: 'english',
    });
    pairsEnsured += 1;
  }

  return {
    anchorEventId: anchor.anchorEventId,
    anchorLessonDate: anchor.anchorLessonDateMoscow,
    syntheticLessonDate: syntheticDateIso,
    eventsEnsured: 1,
    pairsEnsured,
    eligibleStudents: studentIds.length,
  };
}

